apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: fastapi_assistant
    user: user
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
