"""
RAG module: hybrid search (TF-IDF + pgvector), DeepSeek LLM call, and relevance evaluation.
"""

import json
import os
import numpy as np
from time import time
from openai import OpenAI
from typing import List, Dict, Any, Optional

from .minsearch import Index as TextIndex
from . import db
from .vector_store import get_embedder
from .re_ranker import get_reranker
from .load_index import load_text_index as load_pickle_index


# ── DeepSeek Configuration ─────────────────────────────────────────────────────

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_BASE_URL = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-v4-flash")

_openai_client = None

def get_openai_client():
    """Lazy-initialized OpenAI client to avoid import-time errors."""
    global _openai_client
    if _openai_client is None:
        if not DEEPSEEK_API_KEY:
            raise OpenAIError(
                "Missing credentials. Please set DEEPSEEK_API_KEY in .env or "
                "pass an api_key."
            )
        _openai_client = OpenAI(
            api_key=DEEPSEEK_API_KEY,
            base_url=DEEPSEEK_BASE_URL,
        )
    return _openai_client


# ── Text Index (TF-IDF) ────────────────────────────────────────────────────────

text_index = None


def load_text_index():
    """
    Load the in-memory TF-IDF text index from the pre-built pickle file.
    This doesn't require PostgreSQL to be running.
    The pickle was generated by `python -m app.ingest --mode standalone`.
    """
    global text_index
    
    # Load from pickle (standalone mode — no DB needed)
    idx, chunks = load_pickle_index()
    if idx is not None:
        text_index = idx
        return text_index
    
    # Fallback: try loading from pgvector (if DB is initialized)
    try:
        chunks = db.get_all_chunks()
        if chunks:
            text_index = TextIndex(
                text_fields=["title", "heading_path", "content", "section"],
                keyword_fields=["id"],
            )
            text_index.fit(chunks)
            print(f"Loaded text index with {len(chunks)} documents from pgvector")
            return text_index
    except Exception as e:
        print(f"⚠️  Could not load text index from pgvector: {e}")
    
    print("⚠️  No text index available. Run: python -m app.ingest --mode standalone")
    return None


# ── Search Functions ───────────────────────────────────────────────────────────

TEXT_BOOST = {
    "title": 3.0,
    "heading_path": 2.0,
    "content": 1.0,
    "section": 2.5,
}


def minsearch_search(query: str, boost: dict = None) -> List[Dict[str, Any]]:
    """
    Search using TF-IDF text index only.
    """
    if text_index is None:
        load_text_index()
    
    if text_index is None:
        return []
    
    if boost is None:
        boost = TEXT_BOOST
    
    results = text_index.search(
        query=query,
        filter_dict={},
        boost_dict=boost,
        num_results=20,
    )
    return results


def vector_search(query: str) -> List[Dict[str, Any]]:
    """
    Search using pgvector cosine similarity only.
    Falls back to empty results if pgvector is unavailable or not initialized.
    """
    try:
        embedder = get_embedder()
        query_embedding = embedder.embed_query(query)
        results = db.vector_search(query_embedding, limit=20)
        return results
    except Exception as e:
        # Vector search unavailable (pgvector not running, or embedder not installed)
        # This is expected in Docker where torch/onnx are not installed
        return []


def normalize_scores(results: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Normalize scores to [0, 1] range using min-max scaling.
    """
    if not results:
        return results
    
    scores = [r.get("_score", 0) for r in results]
    min_score = min(scores)
    max_score = max(scores)
    
    if max_score == min_score:
        for r in results:
            r["_score_normalized"] = 1.0
        return results
    
    for r in results:
        r["_score_normalized"] = (r.get("_score", 0) - min_score) / (max_score - min_score)
    
    return results


def hybrid_search(query: str, alpha: float = 0.5) -> List[Dict[str, Any]]:
    """
    Hybrid search combining TF-IDF (text) and pgvector (semantic) scores.
    
    hybrid_score = alpha * normalized_text_score + (1 - alpha) * normalized_vector_score
    
    Args:
        query: The search query
        alpha: Weight for text search (0 = pure vector, 1 = pure text, 0.5 = equal)
    
    Returns:
        List of documents with combined hybrid scores, sorted by relevance
    """
    # Get results from both search methods
    text_results = minsearch_search(query)
    vector_results = vector_search(query)
    
    # Normalize scores to [0, 1]
    text_results = normalize_scores(text_results)
    vector_results = normalize_scores(vector_results)
    
    # Build lookup dicts by document ID
    text_by_id = {r["id"]: r for r in text_results}
    vector_by_id = {r["id"]: r for r in vector_results}
    
    # Collect all unique document IDs
    all_ids = set(list(text_by_id.keys()) + list(vector_by_id.keys()))
    
    # Combine scores
    combined = []
    for doc_id in all_ids:
        text_score = text_by_id.get(doc_id, {}).get("_score_normalized", 0)
        vector_score = vector_by_id.get(doc_id, {}).get("_score_normalized", 0)
        
        hybrid_score = alpha * text_score + (1 - alpha) * vector_score
        
        # Get the document data (prefer text result for metadata)
        doc = text_by_id.get(doc_id) or vector_by_id.get(doc_id)
        if doc:
            result = doc.copy()
            result["_text_score"] = text_score
            result["_vector_score"] = vector_score
            result["_score"] = hybrid_score
            combined.append(result)
    
    # Sort by hybrid score descending
    combined.sort(key=lambda x: x["_score"], reverse=True)
    
    return combined[:10]


# ── Query Rewriting ────────────────────────────────────────────────────────────

QUERY_REWRITE_PROMPT = """
You are a search query optimizer for the FastAPI documentation knowledge base.
Rewrite the following user question into a concise, keyword-rich search query 
that will retrieve the most relevant documentation sections.

Rules:
- Keep it concise (5-15 words)
- Include key technical terms (e.g., 'CORS', 'dependency injection', 'TestClient')
- Remove conversational language
- Return ONLY the rewritten query, nothing else

User question: {question}
Optimized search query:
""".strip()


def rewrite_query(question: str) -> str:
    """
    Rewrite/expand a user question into a better search query using the LLM.
    
    Examples:
        "How do I add CORS?" → "FastAPI CORS middleware configuration CORSMiddleware"
        "What is DI?" → "FastAPI dependency injection Depends function parameters"
        "How do I test my API?" → "FastAPI TestClient pytest testing endpoints"
    """
    prompt = QUERY_REWRITE_PROMPT.format(question=question)
    try:
        rewritten, _ = llm(prompt, model=DEEPSEEK_MODEL)
        # Clean up the response
        rewritten = rewritten.strip().strip('"').strip("'").strip()
        return rewritten if rewritten else question
    except Exception as e:
        print(f"⚠️  Query rewriting failed: {e}. Using original query.")
        return question


# ── Prompt Templates ───────────────────────────────────────────────────────────

# Prompt A: Concise (short, direct instruction)
PROMPT_CONCISE = """
You are a FastAPI documentation expert assistant. Answer the QUESTION based on the CONTEXT from the official FastAPI documentation.
Use only the facts from the CONTEXT when answering the QUESTION.
If the CONTEXT doesn't contain the information needed, say "I don't have information about that in the documentation."
Provide code examples where relevant, using Python code blocks.

QUESTION: {question}

CONTEXT:
{context}

Answer:
""".strip()

# Prompt B: Detailed (structured, role-based, with guidelines)
PROMPT_DETAILED = """
You are a Senior FastAPI Documentation Expert with extensive experience teaching developers.

ROLE & PERSONA:
You are patient, thorough, and precise. You always base answers strictly on the provided documentation context. You write answers that are clear to both beginners and experienced Python developers.

TASK:
Answer the USER_QUESTION using ONLY the provided DOCUMENTATION_CONTEXT. If the context lacks sufficient information, say "I don't have complete information about that in the documentation. Based on what I found: ..." and share what you did find.

GUIDELINES:
1. Start with a direct, concise answer to the question.
2. Include relevant code examples using Python code blocks (```python ... ```).
3. Explain any configuration options, parameters, or imports mentioned in the context.
4. If there are multiple valid approaches, mention them briefly.
5. Keep the answer focused strictly on what's in the context. Do not add external knowledge.
6. End with a brief summary or next steps if appropriate.

DOCUMENTATION_CONTEXT:
{context}

USER_QUESTION:
{question}

ANSWER:
""".strip()

entry_template = """
Title: {title}
Section: {section}
Content: {content}
""".strip()

evaluation_prompt_template = """
You are an expert evaluator for a RAG system.
Your task is to analyze the relevance of the generated answer to the given question.
Based on the relevance of the generated answer, you will classify it
as 'NON_RELEVANT', 'PARTLY_RELEVANT', or 'RELEVANT'.

Here is the data for evaluation:

Question: {question}
Generated Answer: {answer}

Please analyze the content and context of the generated answer in relation to the question
and provide your evaluation in parsable JSON without using code blocks:

{{
  'Relevance': 'NON_RELEVANT' | 'PARTLY_RELEVANT' | 'RELEVANT',
  'Explanation': '[Provide a brief explanation for your evaluation]'
}}
""".strip()


# ── Prompt Builder ─────────────────────────────────────────────────────────────

# Map prompt style names to templates
PROMPT_STYLES = {
    "concise": PROMPT_CONCISE,
    "detailed": PROMPT_DETAILED,
}

def build_prompt(query: str, search_results: list, prompt_style: str = "concise") -> str:
    """Build the RAG prompt from query and search results using the specified style.
    
    Args:
        query: The user's question
        search_results: List of retrieved document chunks
        prompt_style: Either "concise" or "detailed"
    
    Returns:
        Formatted prompt string
    """
    context = ""
    for doc in search_results:
        context += entry_template.format(
            title=doc.get("title", ""),
            section=doc.get("section", ""),
            content=doc.get("content", ""),
        ) + "\n\n"
    
    template = PROMPT_STYLES.get(prompt_style, PROMPT_CONCISE)
    prompt = template.format(question=query, context=context).strip()
    return prompt


# ── LLM Call (DeepSeek via Chat Completions) ───────────────────────────────────

def llm(prompt: str, model: str = DEEPSEEK_MODEL):
    """Call DeepSeek via Chat Completions API (OpenAI-compatible)."""
    client = get_openai_client()
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
    )
    
    answer = response.choices[0].message.content
    token_stats = {
        "prompt_tokens": response.usage.prompt_tokens,
        "completion_tokens": response.usage.completion_tokens,
        "total_tokens": response.usage.total_tokens,
    }
    return answer, token_stats


# ── Relevance Evaluation ───────────────────────────────────────────────────────

def evaluate_relevance(question: str, answer: str):
    """Evaluate answer relevance using LLM-as-a-Judge."""
    prompt = evaluation_prompt_template.format(question=question, answer=answer)
    evaluation, tokens = llm(prompt)
    
    try:
        json_eval = json.loads(evaluation)
        return json_eval, tokens
    except json.JSONDecodeError:
        result = {"Relevance": "UNKNOWN", "Explanation": "Failed to parse evaluation"}
        return result, tokens


# ── Cost Calculation ───────────────────────────────────────────────────────────

def calculate_cost(model: str, tokens: dict) -> float:
    """Calculate approximate cost in USD for DeepSeek."""
    cost = 0.0
    model = model.lower()
    
    # DeepSeek pricing (approximate as of 2025)
    if "deepseek" in model:
        cost = (tokens["prompt_tokens"] * 0.14 + tokens["completion_tokens"] * 0.28) / 1_000_000
    
    return cost


# ── Full RAG Pipeline ──────────────────────────────────────────────────────────

def rag(
    query: str,
    model: str = DEEPSEEK_MODEL,
    alpha: float = 0.5,
    prompt_style: str = "concise",
    enable_rerank: bool = True,
    enable_rewrite: bool = True,
) -> dict:
    """
    Run the full RAG pipeline: query rewrite → hybrid search → re-rank → build prompt → DeepSeek LLM → evaluate.
    
    Args:
        query: The user's question
        model: The DeepSeek model to use
        alpha: Hybrid search weight (0 = pure vector, 1 = pure text)
        prompt_style: Either "concise" or "detailed"
        enable_rerank: Whether to apply cross-encoder re-ranking after search
        enable_rewrite: Whether to rewrite/expand the query before search
    
    Returns:
        Dict with answer, metadata, retrieval results, and evaluation
    """
    t0 = time()
    
    # Step 0: Query rewriting (improves search by expanding user query)
    search_query = query
    if enable_rewrite:
        search_query = rewrite_query(query)
        if search_query != query:
            print(f"   🔄 Rewritten query: '{query}' → '{search_query}'")
    
    # Step 1: Hybrid search (TF-IDF + pgvector)
    search_results = hybrid_search(search_query, alpha=alpha)
    
    # Step 1.5: Re-ranking (cross-encoder for more accurate ordering)
    if enable_rerank and search_results:
        try:
            reranker = get_reranker()
            if reranker.model is not None:
                search_results = reranker.rerank(query, search_results, top_k=10)
        except Exception as e:
            print(f"   ⚠️  Re-ranking skipped: {e}")
    
    # Step 2: Build prompt with context
    prompt = build_prompt(query, search_results, prompt_style=prompt_style)
    
    # Step 3: Call DeepSeek LLM
    answer, token_stats = llm(prompt, model=model)
    
    # Step 4: Evaluate relevance
    relevance, rel_token_stats = evaluate_relevance(query, answer)
    
    t1 = time()
    took = t1 - t0
    
    # Step 5: Calculate costs
    cost_rag = calculate_cost(model, token_stats)
    cost_eval = calculate_cost(model, rel_token_stats)
    total_cost = cost_rag + cost_eval
    
    return {
        "answer": answer,
        "model_used": model,
        "response_time": took,
        "relevance": relevance.get("Relevance", "UNKNOWN"),
        "relevance_explanation": relevance.get("Explanation", "Failed to parse"),
        "prompt_tokens": token_stats["prompt_tokens"],
        "completion_tokens": token_stats["completion_tokens"],
        "total_tokens": token_stats["total_tokens"],
        "eval_prompt_tokens": rel_token_stats["prompt_tokens"],
        "eval_completion_tokens": rel_token_stats["completion_tokens"],
        "eval_total_tokens": rel_token_stats["total_tokens"],
        "openai_cost": total_cost,
        "retrieved_chunks": [
            {
                "id": r["id"],
                "title": r["title"],
                "section": r["section"],
                "url": r["url"],
                "score": r["_score"],
            }
            for r in search_results[:5]  # Top 5 chunks
        ],
    }


# ── Search-only function for retrieval evaluation ──────────────────────────────

def search_only(query: str, method: str = "hybrid", alpha: float = 0.5) -> list:
    """
    Search only (no LLM) — used for retrieval evaluation.
    
    Args:
        query: The search query
        method: One of "text", "vector", or "hybrid"
        alpha: Hybrid search weight (only used if method="hybrid")
    
    Returns:
        List of document results
    """
    if method == "text":
        return minsearch_search(query)
    elif method == "vector":
        return vector_search(query)
    else:  # hybrid
        return hybrid_search(query, alpha=alpha)